import os

srcs=Split("""
apitable.c
attribute.c
backdoor.c
camera.c
context.c
declare.c
display.c
lightsource.c
option.c
quadric.c
ri.c
subdivision.c
transform.c
""")

Import('env')

incPath=['../base', '../transport', '../render', '../ri', '../../include']
libName='riri'

l = env.Library(libName, srcs, CPPPATH=incPath)

if env['PREFIX'] == None:
  # install locally
  install_libdir = "../../lib"
else:
  install_libdir = os.path.join(env['PREFIX'], "lib")

install_lib = env.Install(install_libdir, l)

Default(install_lib)

