######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 31 00:31:07 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
