// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "gui.h"
#include <stdio.h>
#include <stdlib.h>
#include "callbacks.h"

Fl_Double_Window *renderWindow=(Fl_Double_Window *)0;

static void cb_Open(Fl_Menu_*, void*) {
  handleOpenRSL();
}

static void cb_Quit(Fl_Menu_*, void*) {
  exit(1);
}

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Open RSL", 0x6f,  (Fl_Callback*)cb_Open, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", 0x71,  (Fl_Callback*)cb_Quit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

MyGLWindow *GLWindow=(MyGLWindow *)0;

Fl_Double_Window* makeRenderWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = renderWindow = new Fl_Double_Window(405, 320);
    w = o;
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 565, 25);
      o->menu(menu_);
    }
    { Fl_Group* o = new Fl_Group(5, 30, 555, 425);
      { MyGLWindow* o = GLWindow = new MyGLWindow(5, 30, 256, 256, "GLWindow");
        o->box(FL_NO_BOX);
        o->color(FL_BACKGROUND_COLOR);
        o->selection_color(FL_BACKGROUND_COLOR);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(14);
        o->labelcolor(FL_FOREGROUND_COLOR);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      o->end();
    }
    o->end();
  }
  return w;
}

Fl_Double_Window *shaderWindow=(Fl_Double_Window *)0;

Fl_Tabs *shaderDisplayTab=(Fl_Tabs *)0;

Fl_Text_Display *rslTextDisplay=(Fl_Text_Display *)0;

Fl_Text_Display *llvmTextDisplay=(Fl_Text_Display *)0;

static void cb_Compile(Fl_Button*, void*) {
  compile_cb();
}

Fl_Output *outputCompileResult=(Fl_Output *)0;

Fl_Double_Window* makeShaderWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = shaderWindow = new Fl_Double_Window(550, 480);
    w = o;
    { Fl_Tabs* o = shaderDisplayTab = new Fl_Tabs(5, 5, 540, 415);
      { Fl_Group* o = new Fl_Group(5, 35, 540, 385, "RSL");
        { Fl_Text_Display* o = rslTextDisplay = new Fl_Text_Display(10, 40, 530, 375);
          o->labelfont(13);
          o->labelsize(9);
          o->textfont(13);
          o->textsize(12);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(5, 35, 540, 385, "LLVM IR");
        o->hide();
        llvmTextDisplay = new Fl_Text_Display(10, 40, 530, 375);
        o->end();
      }
      o->end();
    }
    { Fl_Button* o = new Fl_Button(10, 440, 80, 25, "Compile");
      o->callback((Fl_Callback*)cb_Compile);
    }
    { Fl_Output* o = outputCompileResult = new Fl_Output(105, 440, 120, 25);
      o->box(FL_THIN_DOWN_BOX);
    }
    o->end();
  }
  return w;
}
Fl_Text_Buffer *rslTextBuf;
Fl_Text_Buffer *llvmTextBuf;
