// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *renderWindow;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include "MyGLWindow.h"
extern MyGLWindow *GLWindow;
Fl_Double_Window* makeRenderWindow();
extern Fl_Menu_Item menu_[];
extern Fl_Double_Window *shaderWindow;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *shaderDisplayTab;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *rslTextDisplay;
extern Fl_Text_Display *llvmTextDisplay;
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
extern Fl_Output *outputCompileResult;
Fl_Double_Window* makeShaderWindow();
extern Fl_Text_Buffer *rslTextBuf;
extern Fl_Text_Buffer *llvmTextBuf;
#endif
