// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *renderWindow;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include "MyGLWindow.h"
extern MyGLWindow *GLWindow;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *buttonSpecialization;
extern Fl_Light_Button *button4x4Update;
#include <FL/Fl_Output.H>
extern Fl_Output *secDisplay;
Fl_Double_Window* makeRenderWindow();
extern Fl_Menu_Item menu_[];
extern Fl_Double_Window *shaderWindow;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *shaderDisplayTab;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *rslTextDisplay;
extern Fl_Text_Display *llvmTextDisplay;
Fl_Double_Window* makeShaderWindow();
extern Fl_Text_Buffer *rslTextBuf; 
extern Fl_Text_Buffer *llvmTextBuf; 
#endif
