
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[479] =
    {   0,
       76,   76,    0,    0,    0,    0,   76,   76,   81,   79,
       76,   77,   79,    1,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,    2,    3,   73,   74,   72,   73,   61,   79,
       79,   75,   59,   60,   76,   78,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   71,
       70,   67,   71,   68,   65,   66,   62,   64,   63,    0,
       75,   75,   75,    0,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,    0,   75,    0,   75,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       69,   58,   58,   58,   58,   10,   58,   58,   58,   58,
       58,   58,   58,   58,   22,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   41,   58,   58,   58,   46,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   21,   58,   58,   58,   58,   58,   25,   58,
       58,   58,   30,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   40,   58,   58,   58,   47,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       13,   58,   58,   16,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   29,   58,   58,   58,   58,   58,   58,
       37,   58,   58,   58,   58,   58,   45,   58,   49,   58,

       58,   58,   58,   54,   58,   58,   58,    9,   58,   58,
       58,   58,   17,   58,   58,   19,   23,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   39,   58,
       58,   58,   58,   58,   58,   58,   58,   56,   58,   58,
        5,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       28,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   50,   53,   58,   58,    8,   58,   58,
       58,   58,   58,   58,   58,   18,   24,   58,   58,   58,
       58,   58,   58,   58,   58,   38,   58,   58,   58,   58,
       58,   58,   58,   55,   58,   58,   58,   58,   58,   58,

       58,   58,   26,   27,   31,   32,   33,   58,   58,   58,
       58,   58,   58,   44,   58,   58,   58,   58,   58,    7,
       58,   58,   14,   15,   58,   34,   58,   58,    0,    0,
       42,   58,   58,   58,   52,   58,   58,   58,   58,   58,
       58,   58,    0,   57,   58,   58,   58,   58,    6,   58,
       58,   58,   58,   35,   58,   58,   51,    4,   11,   58,
       58,   58,   58,   48,   12,   20,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   43,   36,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    7,    1,    7,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        1,    1,    1,    1,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   19,   20,   21,   19,   22,   23,
       24,   25,   26,   27,   19,   19,   28,   19,   19,   19,
       29,   30,   31,    1,   19,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   19,   42,   43,   44,
       45,   46,   19,   47,   48,   49,   50,   51,   52,   53,
       54,   55,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[56] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[484] =
    {   0,
        0,    0,  533,  532,   53,   54,   56,   61,  534,  537,
      531,  537,  529,  537,   13,    0,   29,   36,  478,   28,
      490,   46,  489,  483,   31,   46,  477,   58,   61,  479,
      480,  488,  537,  537,  537,  537,  537,  109,  537,   71,
      514,   88,  537,  537,  520,  537,    0,  485,   55,  480,
       64,   71,  471,  472,  470,  484,  480,  478,  471,  480,
      473,  461,   67,  469,  461,  454,   73,  461,  473,  472,
      454,   78,   87,  467,  462,   87,  468,  452,  451,  537,
      537,  537,  488,  537,  537,  537,  537,  537,  537,  487,
      113,  114,  121,  122,  463,  449,  446,  446,  446,  456,

      442,  446,  438,  440,  440,  441,  440,  446,  437,  430,
      441,  439,  437,  442,  435,  438,  425,  436,  427,  416,
      428,  424,  432,  434,  423,  428,  428,  413,  425,  424,
      424,  421,  413,  414,  407,  445,  124,  444,  443,  431,
      402,  409,  402,  400,  414,  410,  412,  404,  400,  393,
      408,  403,  391,  388,  393,  399,  385,  388,  392,  386,
      386,  383,  386,  378,  388,  389,  375,  413,  373,  385,
      384,  379,  369,  369,  369,  375,  382,  365,  377,  371,
      537,  370,  363,  375,  367,    0,  357,  365,  357,  381,
      370,  351,  351,  130,    0,  359,  358,  350,  370,  351,

      345,  349,  343,  355,  117,  342,  344,  354,  347,  339,
      349,    0,  340,  339,  346,    0,  345,  329,  345,  110,
      134,  333,  339,  337,  325,  330,  346,  328,  335,  333,
      117,  322,    0,  320,  331,  322,  316,  320,    0,  318,
      148,  308,    0,  329,  326,  319,  326,  138,  313,  307,
      300,  320,    0,  325,  314,  304,    0,  310,  313,  303,
      315,  310,  301,  300,  304,  306,  292,  302,  292,  306,
        0,  322,  300,    0,  299,  288,  295,  297,  277,  298,
      279,  292,  283,    0,  277,  276,  282,  280,  286,  276,
        0,  280,  283,  279,  277,  145,    0,  268,    0,  268,

      265,  275,  277,    0,  262,  263,  273,    0,  276,  258,
      266,  262,    0,  268,  263,    0,    0,  253,  254,  262,
      264,  258,  257,  247,  249,  250,  251,  247,    0,  251,
      246,  245,  256,  247,  243,  249,  244,    0,  257,  246,
      153,  237,  244,  243,  242,  243,  232,  239,  240,  233,
        0,  227,  220,  234,  227,  232,  213,  222,  214,  229,
      214,  213,  216,  154,    0,  216,  214,    0,  222,  213,
      208,  229,  212,  209,  203,    0,    0,  215,  206,  205,
      212,  200,  210,  198,  206,    0,  207,  197,  205,  204,
      195,  202,  193,    0,  186,  197,  199,  196,  178,  196,

      181,  204,    0,    0,    0,    0,    0,  180,  195,  181,
      164,  173,  177,    0,  202,  184,  186,  173,  179,    0,
      173,  169,    0,    0,  184,    0,  173,  170,  170,  208,
        0,  166,  175,  170,    0,  175,  164,  160,  157,  156,
      181,  155,  197,  537,  156,  152,  155,  162,    0,  154,
      160,  155,  149,    0,  151,  153,    0,    0,    0,  148,
      145,  147,  156,    0,    0,    0,  133,  137,  147,  144,
      129,  128,  111,   92,   78,    0,    0,  537,  175,  177,
       65,  179,  181
    } ;

static yyconst flex_int16_t yy_def[484] =
    {   0,
      478,    1,  479,  479,  480,  480,    1,    1,  478,  478,
      478,  478,  478,  478,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  478,  478,  478,  478,  478,  482,  478,  478,
      478,  478,  478,  478,  478,  478,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  478,  478,  478,  478,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      478,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  478,  483,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  483,  478,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,    0,  478,  478,
      478,  478,  478
    } ;

static yyconst flex_int16_t yy_nxt[593] =
    {   0,
       10,   11,   12,   13,   10,   14,   10,   10,   10,   15,
       16,   17,   18,   19,   20,   16,   21,   22,   16,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   10,   10,
       10,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       32,   16,   16,   16,   16,   36,   36,   37,   37,   48,
       39,   49,   40,   41,   42,   39,   47,   40,   41,   42,
       50,   52,   55,   51,   56,   53,   63,   64,   90,   91,
       58,   65,   38,   38,   43,   66,   44,   59,   60,   43,
       67,   44,   68,   70,   72,   93,   91,   96,  114,   73,

       74,   94,   71,   97,  102,   99,   75,  100,  101,  125,
       76,   81,  119,   82,  120,  115,  103,   83,  127,  131,
       93,   91,   92,   94,  126,  477,   94,   94,  138,  137,
      139,  246,  137,  132,   94,  476,  128,   94,   84,  234,
      235,   85,  247,  236,  262,   86,  260,  263,   94,   94,
      273,  261,   87,  289,  475,   88,   94,   89,  282,   94,
      290,  283,  332,  369,  392,  429,  370,  393,  430,  333,
      274,  429,  474,  473,  430,   33,   33,   35,   35,   80,
       80,  443,  443,  472,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  460,  459,  458,  457,  456,

      455,  444,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  442,  441,  440,  439,  438,  437,  436,
      435,  434,  433,  432,  431,  428,  427,  426,  425,  424,
      423,  422,  421,  420,  419,  418,  417,  416,  415,  414,
      413,  412,  411,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  395,  394,
      391,  390,  389,  388,  387,  386,  385,  384,  383,  382,
      381,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      371,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,

      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  288,  287,  286,
      285,  284,  281,  280,  279,  278,  277,  276,  275,  272,
      271,  270,  269,  268,  267,  266,  265,  264,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  233,

      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  139,  139,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,   92,  136,  135,  134,  133,

      130,  129,  124,  123,  122,  121,  118,  117,  116,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,   98,
       95,   45,   92,   79,   78,   77,   69,   62,   61,   57,
       54,   46,   45,  478,   34,   34,    9,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478

    } ;

static yyconst flex_int16_t yy_chk[593] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    6,    5,    6,   15,
        7,   15,    7,    7,    7,    8,  481,    8,    8,    8,
       17,   18,   20,   17,   20,   18,   25,   25,   40,   40,
       22,   26,    5,    6,    7,   26,    7,   22,   22,    8,
       26,    8,   26,   28,   29,   42,   42,   49,   63,   29,

       29,   42,   28,   49,   52,   51,   29,   51,   51,   72,
       29,   38,   67,   38,   67,   63,   52,   38,   73,   76,
       91,   91,   92,   42,   72,  475,   91,   92,   94,   93,
       94,  205,  137,   76,   93,  474,   73,  137,   38,  194,
      194,   38,  205,  194,  221,   38,  220,  221,   91,   92,
      231,  220,   38,  248,  473,   38,   93,   38,  241,  137,
      248,  241,  296,  341,  364,  411,  341,  364,  411,  296,
      231,  429,  472,  471,  429,  479,  479,  480,  480,  482,
      482,  483,  483,  470,  469,  468,  467,  463,  462,  461,
      460,  456,  455,  453,  452,  451,  450,  448,  447,  446,

      445,  443,  442,  441,  440,  439,  438,  437,  436,  434,
      433,  432,  430,  428,  427,  425,  422,  421,  419,  418,
      417,  416,  415,  413,  412,  410,  409,  408,  402,  401,
      400,  399,  398,  397,  396,  395,  393,  392,  391,  390,
      389,  388,  387,  385,  384,  383,  382,  381,  380,  379,
      378,  375,  374,  373,  372,  371,  370,  369,  367,  366,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  340,  339,  337,  336,  335,  334,  333,  332,  331,
      330,  328,  327,  326,  325,  324,  323,  322,  321,  320,

      319,  318,  315,  314,  312,  311,  310,  309,  307,  306,
      305,  303,  302,  301,  300,  298,  295,  294,  293,  292,
      290,  289,  288,  287,  286,  285,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  273,  272,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      256,  255,  254,  252,  251,  250,  249,  247,  246,  245,
      244,  242,  240,  238,  237,  236,  235,  234,  232,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  219,  218,
      217,  215,  214,  213,  211,  210,  209,  208,  207,  206,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  193,

      192,  191,  190,  189,  188,  187,  185,  184,  183,  182,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,  152,  151,
      150,  149,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  136,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  120,
      119,  118,  117,  116,  115,  114,  113,  112,  111,  110,
      109,  108,  107,  106,  105,  104,  103,  102,  101,  100,
       99,   98,   97,   96,   95,   90,   83,   79,   78,   77,

       75,   74,   71,   70,   69,   68,   66,   65,   64,   62,
       61,   60,   59,   58,   57,   56,   55,   54,   53,   50,
       48,   45,   41,   32,   31,   30,   27,   24,   23,   21,
       19,   13,   11,    9,    4,    3,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lsh/lexrib.l"
#line 2 "src/lsh/lexrib.l"
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef WITH_DMALLOC
#include <dmalloc.h>
#endif

#include "memory.h"
#include "array.h"
#include "parserib.h"
#include "render.h"

#define YY_MALLOC_DECL

/* for ReadArchive */
typedef struct _ribstack_t
{
    int                 line_num;
    const char         *rib;
    YY_BUFFER_STATE     state;
    struct _ribstack_t *next;
} ribstack_t;

static ribstack_t *ribstack = NULL;
static const char *gribfile = NULL;

int line_num = 0;
int str_pos;

int lexrib_mode_param;
int lexrib_mode_skip;

static FILE *ribin;

void add_string_char(char c)
{
    yylval.string[str_pos++] = c;
    yylval.string[str_pos]   = '\0';
}

static void read_archive(const char *rib)
{
    FILE            *fp;
    YY_BUFFER_STATE  state;
    ribstack_t      *stack;
    ri_option_t     *opt;
    char             fullpath[1024];

    if (!rib) return;

    if (rib[0] == '\0') return;

#ifdef DEBUG
    fprintf(stdout, "ReadArchive = %s\n", rib); 
#endif
    

    opt = ri_render_get()->context->option;

    if (!ri_option_find_file(fullpath, opt, rib)) {
        fprintf(stderr,
                "[warning] ReadArchive: Can't open RIB \"%s\"\n",
            rib);
        ri_option_show_searchpath(opt);
        return;
    } else {
        fp = fopen(fullpath, "r");
        if (!fp) {
            fprintf(stderr,
                "[warning] ReadArchive: Can't open RIB ");
            fprintf(stderr,
                "\"%s\"\n", rib);
            return;
        }
    }

    stack = (ribstack_t *)ri_mem_alloc(sizeof(ribstack_t));
    stack->state = YY_CURRENT_BUFFER;
    stack->rib   = gribfile;
    stack->next  = ribstack;
    ribstack     = stack;

    state = yy_create_buffer(fp,YY_BUF_SIZE);

    /* Change reading input RIB file. */
    yy_switch_to_buffer(state);

    ribin = fp;

    /* tear down is done in <<EOF>> pattern */
}




#line 846 "<stdout>"

#define INITIAL 0
#define COMMENT 1
#define STR 2
#define PARAM 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 108 "src/lsh/lexrib.l"

    if (lexrib_mode_skip) {
        BEGIN INITIAL;
        lexrib_mode_skip = 0;
    }
    
    if (lexrib_mode_param) {
        BEGIN PARAM;
        lexrib_mode_param = 0;
    }

#line 1022 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 479 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 537 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 119 "src/lsh/lexrib.l"
{ BEGIN COMMENT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 120 "src/lsh/lexrib.l"
/* skip all character */
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 121 "src/lsh/lexrib.l"
{ line_num++; BEGIN INITIAL;                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 122 "src/lsh/lexrib.l"
{ return AREALIGHTSOURCE;                           }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 123 "src/lsh/lexrib.l"
{ return ATTRIBUTE;                                 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 124 "src/lsh/lexrib.l"
{ return ATTRIBUTEBEGIN;                            }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 125 "src/lsh/lexrib.l"
{ return ATTRIBUTEEND;                              }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 126 "src/lsh/lexrib.l"
{ return ATMOSPHERE;                                }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 127 "src/lsh/lexrib.l"
{ return CLIPPING;                                  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 128 "src/lsh/lexrib.l"
{ return COLOR;                                     }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 129 "src/lsh/lexrib.l"
{ return CONCATTRANSFORM;                           }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 130 "src/lsh/lexrib.l"
{ return COORDINATESYSTEM;                          }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 131 "src/lsh/lexrib.l"
{ return DECLARE;                                   }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 132 "src/lsh/lexrib.l"
{ return DEPTHOFFIELD;                              }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 133 "src/lsh/lexrib.l"
{ return DISPLACEMENT;                              }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "src/lsh/lexrib.l"
{ return DISPLAY;                                   }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 135 "src/lsh/lexrib.l"
{ return EXPOSURE;                                  }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 136 "src/lsh/lexrib.l"
{ return FRAMEBEGIN;                                }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 137 "src/lsh/lexrib.l"
{ return FRAMEEND;                                  }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 138 "src/lsh/lexrib.l"
{ return FRAMEASPECTRATIO;                          }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 139 "src/lsh/lexrib.l"
{ return FORMAT;                                    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 140 "src/lsh/lexrib.l"
{ return HIDER;                                     }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 141 "src/lsh/lexrib.l"
{ return IDENTITY;                                  }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 142 "src/lsh/lexrib.l"
{ return ILLUMINATE;                                }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 143 "src/lsh/lexrib.l"
{ return IMAGER;                                    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 144 "src/lsh/lexrib.l"
{ return LIGHTSOURCE;                               }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 145 "src/lsh/lexrib.l"
{ return MOTIONBEGIN;                               }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 146 "src/lsh/lexrib.l"
{ return MOTIONEND;                                 }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 147 "src/lsh/lexrib.l"
{ return OPACITY;                                   }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 148 "src/lsh/lexrib.l"
{ return OPTION;                                    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 149 "src/lsh/lexrib.l"
{ return ORIENTATION;                               }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 150 "src/lsh/lexrib.l"
{ return PERSPECTIVE;                               }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 151 "src/lsh/lexrib.l"
{ return PIXELFILTER;                               }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 152 "src/lsh/lexrib.l"
{ return PIXELSAMPLES;                              }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 153 "src/lsh/lexrib.l"
{ return POINTSPOLYGONS;                            }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 154 "src/lsh/lexrib.l"
{ return POINTSGENERALPOLYGONS;                     }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 155 "src/lsh/lexrib.l"
{ return POLYGON;                                   }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 156 "src/lsh/lexrib.l"
{ return PROJECTION;                                }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 157 "src/lsh/lexrib.l"
{ return QUANTIZE;                                  }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 158 "src/lsh/lexrib.l"
{ return ROTATE;                                    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 159 "src/lsh/lexrib.l"
{ return SCALE;                                     }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 160 "src/lsh/lexrib.l"
{ return SCREENWINDOW;                              }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 161 "src/lsh/lexrib.l"
{ return SHADINGINTERPOLATION;                      }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 162 "src/lsh/lexrib.l"
{ return SHADINGRATE;                               }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 163 "src/lsh/lexrib.l"
{ return SHUTTER;                                   }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 164 "src/lsh/lexrib.l"
{ return SIDES;                                     }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 165 "src/lsh/lexrib.l"
{ return SPHERE;                                    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 166 "src/lsh/lexrib.l"
{ return SUBDIVISIONMESH;                           }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 167 "src/lsh/lexrib.l"
{ return SURFACE;                                   }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 168 "src/lsh/lexrib.l"
{ return TRANSFORM;                                 }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 169 "src/lsh/lexrib.l"
{ return TRANSFORMBEGIN;                            }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 170 "src/lsh/lexrib.l"
{ return TRANSFORMEND;                              }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 171 "src/lsh/lexrib.l"
{ return TRANSLATE;                                 }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 172 "src/lsh/lexrib.l"
{ return RIBVERSION;                                }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 173 "src/lsh/lexrib.l"
{ return WORLDBEGIN;                                }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 174 "src/lsh/lexrib.l"
{ return WORLDEND;                                  }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 176 "src/lsh/lexrib.l"
{
    char buf[1024];
    sscanf(yytext, "ReadArchive \"%s\"", buf);
    /* '\"' -> '\0' */
    buf[strlen(buf)-1] = '\0';
    read_archive(buf);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 183 "src/lsh/lexrib.l"
{ strcpy(yylval.string, yytext);
                      return UNKNOWN;                                       }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 185 "src/lsh/lexrib.l"
{ return LBRACKET;                                      }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 186 "src/lsh/lexrib.l"
{ return RBRACKET;                                      }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 187 "src/lsh/lexrib.l"
{ str_pos = 0; yy_push_state(STR);                      }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 188 "src/lsh/lexrib.l"
{ add_string_char('\n');                                }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 189 "src/lsh/lexrib.l"
{ add_string_char('\t');                                }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 190 "src/lsh/lexrib.l"
{ add_string_char('\r');                                }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 191 "src/lsh/lexrib.l"
{ add_string_char('\b');                                }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 192 "src/lsh/lexrib.l"
{ add_string_char('\f');                                }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 193 "src/lsh/lexrib.l"
{ add_string_char('\"');                                }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 194 "src/lsh/lexrib.l"
{ add_string_char('\\');                                }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 195 "src/lsh/lexrib.l"
{
    int val = atoi(yytext + 1);
    while (val > 256) val -= 256;
    add_string_char(val);
}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 200 "src/lsh/lexrib.l"
{ line_num++;                                           }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 201 "src/lsh/lexrib.l"
{ add_string_char(yytext[1]);                           }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 202 "src/lsh/lexrib.l"
{ yy_pop_state(); return STRING;                        }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 203 "src/lsh/lexrib.l"
{ add_string_char(yytext[0]);                           }
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 204 "src/lsh/lexrib.l"
{ printf("unterminated string!");                       }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 205 "src/lsh/lexrib.l"
{
    yylval.num = atof(yytext);
    return NUM;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 209 "src/lsh/lexrib.l"
/* skip */
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 210 "src/lsh/lexrib.l"
{ line_num++;                                           }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 211 "src/lsh/lexrib.l"
{ line_num++;                                           }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 212 "src/lsh/lexrib.l"
{ printf( "[RIB parse] Illegal character: %c at line %d\n",yytext[0], line_num ); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(PARAM):
#line 213 "src/lsh/lexrib.l"
{
    if (ribstack) {
        ribstack_t *next = ribstack->next;

        yy_delete_buffer(YY_CURRENT_BUFFER);
        fclose(ribin);
        yy_switch_to_buffer(ribstack->state);

        gribfile = ribstack->rib;

        free(ribstack);
        ribstack = next;
    } else {
        yyterminate();
    }
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 229 "src/lsh/lexrib.l"
ECHO;
	YY_BREAK
#line 1547 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 479 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 479 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 478);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 229 "src/lsh/lexrib.l"



