/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/root/flex/flex/skel.c,v 1.1.1.1 1999/04/23 00:46:30 wsanchez Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
static yyconst short int yy_accept[455] =
    {   0,
       73,   73,    0,    0,    0,    0,   73,   73,   78,   76,
       73,   74,   76,    1,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,    2,    3,   70,   71,   69,   70,   58,   76,
       76,   72,   56,   57,   73,   75,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   68,
       67,   64,   68,   65,   62,   63,   59,   61,   60,    0,
       72,   72,   72,    0,   55,   55,   55,   55,   55,   55,

       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,    0,   72,    0,   72,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   66,   55,   55,   55,
        9,   55,   55,   55,   55,   55,   55,   55,   55,   20,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,   55,   55,   55,   55,   39,   55,   55,   43,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   19,   55,   55,   55,   55,
       55,   23,   55,   55,   55,   28,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   38,   55,   55,   44,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   12,   55,   14,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   27,   55,   55,   55,   55,   55,   55,
       35,   55,   55,   55,   55,   42,   55,   46,   55,   55,
       55,   55,   51,   55,   55,    8,   55,   55,   55,   15,

       55,   55,   17,   21,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   37,   55,   55,   55,   55,
       55,   55,   55,   53,   55,    5,   55,   55,   55,   55,
       55,   55,   55,   55,   26,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   47,   50,   55,   55,
       55,   55,   55,   55,   55,   55,   16,   22,   55,   55,
       55,   55,   55,   55,   55,   55,   36,   55,   55,   55,
       55,   55,   55,   52,   55,   55,   55,   55,   55,   55,
       55,   24,   25,   29,   30,   31,   55,   55,   55,   55,
       55,   41,   55,   55,   55,   55,   55,    7,   55,   55,

       13,   55,   32,   55,   55,    0,    0,   55,   55,   55,
       49,   55,   55,   55,   55,   55,   55,   55,    0,   54,
       55,   55,   55,   55,    6,   55,   55,   55,   55,   33,
       55,   55,   48,    4,   10,   55,   55,   55,   55,   45,
       11,   18,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   40,   34,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    7,    1,    7,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        1,    1,    1,    1,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   19,   20,   21,   19,   22,   23,
       24,   25,   26,   27,   19,   19,   28,   19,   19,   19,
       29,   30,   31,    1,   19,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   19,   42,   43,   44,
       45,   46,   19,   47,   48,   49,   50,   51,   19,   52,
       53,   54,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2
    } ;

static yyconst short int yy_base[460] =
    {   0,
        0,    0,  508,  507,   52,   53,   55,   60,  509,  512,
      506,  512,  504,  512,   12,    0,   28,   35,  454,   27,
      465,   45,  464,  458,   30,   45,  452,   57,   60,  454,
      455,  463,  512,  512,  512,  512,  512,  108,  512,   70,
      489,   87,  512,  512,  495,  512,    0,  460,  446,  454,
       63,   63,  445,  446,  444,  458,  454,  452,  445,  454,
      447,  435,   66,  443,  435,  429,   72,  435,  447,  446,
      428,  444,   71,  440,  435,   71,  441,  425,  424,  512,
      512,  512,  461,  512,  512,  512,  512,  512,  512,  460,
      111,  113,  115,  119,  436,  420,  420,  420,  430,  416,

      420,  412,  414,  414,  415,  414,  420,  411,  404,  415,
      413,  411,  416,  409,  412,  399,  410,  401,  391,  402,
      398,  406,  408,  397,  403,  388,  400,  399,  399,  396,
      388,  389,  382,  420,  122,  419,  418,  406,  385,  378,
      376,  390,  386,  388,  380,  376,  369,  384,  379,  367,
      364,  369,  375,  361,  364,  368,  362,  362,  359,  362,
      354,  364,  365,  351,  389,  349,  361,  356,  346,  346,
      346,  352,  359,  342,  354,  348,  512,  347,  353,  345,
        0,  335,  343,  335,  359,  348,  329,  329,  123,    0,
      337,  336,  328,  348,  329,  323,  327,  321,  333,  117,

      320,  322,  332,  325,  317,  327,    0,  318,  325,    0,
      324,  308,  324,   93,  128,  312,  318,  305,  310,  326,
      308,  315,  313,  296,  301,    0,  299,  310,  301,  295,
      299,    0,  297,  139,  288,    0,  308,  305,  298,  305,
      138,  292,  286,  280,  299,    0,  294,  284,    0,  290,
      293,  283,  295,  290,  281,  280,  284,  273,  283,  273,
      287,    0,  303,    0,  281,  270,  277,  279,  260,  280,
      261,  274,  265,    0,  259,  258,  264,  262,  268,  258,
        0,  262,  265,  261,  138,    0,  251,    0,  251,  248,
      258,  260,    0,  245,  257,    0,  260,  242,  250,    0,

      253,  248,    0,    0,  238,  239,  247,  249,  243,  242,
      232,  234,  235,  236,  232,    0,  236,  231,  242,  233,
      229,  235,  230,    0,  243,  148,  224,  231,  230,  231,
      220,  227,  228,  221,    0,  215,  208,  222,  215,  220,
      202,  210,  202,  203,  202,  205,  153,    0,  205,  203,
      211,  202,  197,  218,  201,  193,    0,    0,  205,  196,
      195,  202,  190,  200,  188,  196,    0,  197,  196,  195,
      186,  193,  184,    0,  177,  188,  190,  187,  170,  187,
      196,    0,    0,    0,    0,    0,  172,  187,  173,  163,
      170,    0,  195,  177,  179,  166,  172,    0,  166,  162,

        0,  177,    0,  166,  163,  164,  201,  159,  168,  163,
        0,  168,  157,  153,  150,  149,  174,  148,  190,  512,
      149,  145,  148,  155,    0,  147,  153,  148,  142,    0,
      144,  146,    0,    0,    0,  141,  138,  140,  149,    0,
        0,    0,  127,  130,  140,  120,  103,  101,  100,   96,
       68,    0,    0,  512,  169,  171,   64,  173,  175
    } ;

static yyconst short int yy_def[460] =
    {   0,
      454,    1,  455,  455,  456,  456,    1,    1,  454,  454,
      454,  454,  454,  454,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  454,  454,  454,  454,  454,  458,  454,  454,
      454,  454,  454,  454,  454,  454,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  457,  457,  457,  457,  457,  457,

      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  454,  454,  454,  454,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  454,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,

      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,

      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,

      457,  457,  457,  457,  457,  454,  459,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  459,  454,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,    0,  454,  454,  454,  454,  454
    } ;

static yyconst short int yy_nxt[567] =
    {   0,
       10,   11,   12,   13,   10,   14,   10,   10,   10,   15,
       16,   17,   18,   19,   20,   16,   21,   22,   16,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   10,   10,
       10,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       32,   16,   16,   16,   36,   36,   37,   37,   48,   39,
       49,   40,   41,   42,   39,   47,   40,   41,   42,   50,
       52,   55,   51,   56,   53,   63,   64,   90,   91,   58,
       65,   38,   38,   43,   66,   44,   59,   60,   43,   67,
       44,   68,   70,   72,   93,   91,  101,  113,   73,   74,

       94,   71,  125,  129,   98,   75,   99,  100,  102,   76,
       81,  118,   82,  119,  114,  453,   83,  130,   93,   91,
      126,   92,   94,  135,   94,  136,   94,  137,   94,  252,
      135,  239,  227,  228,  253,   94,  229,   84,  254,  452,
       85,  255,  240,  451,   86,  450,   94,  449,   94,  272,
       94,   87,  273,  279,   88,  318,   89,   94,  351,  448,
      280,  352,  319,  372,  406,  406,  373,  407,  407,   33,
       33,   35,   35,   80,   80,  419,  419,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  435,
      434,  433,  432,  431,  420,  430,  429,  428,  427,  426,

      425,  424,  423,  422,  421,  420,  418,  417,  416,  415,
      414,  413,  412,  411,  410,  409,  408,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  317,

      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  278,  277,  276,  275,
      274,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,

      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  137,  137,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  140,  139,  138,   92,  134,
      133,  132,  131,  128,  127,  124,  123,  122,  121,  120,
      117,  116,  115,  112,  111,  110,  109,  108,  107,  106,
      105,  104,  103,   97,   96,   95,   45,   92,   79,   78,

       77,   69,   62,   61,   57,   54,   46,   45,  454,   34,
       34,    9,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454
    } ;

static yyconst short int yy_chk[567] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    6,    5,    6,   15,    7,
       15,    7,    7,    7,    8,  457,    8,    8,    8,   17,
       18,   20,   17,   20,   18,   25,   25,   40,   40,   22,
       26,    5,    6,    7,   26,    7,   22,   22,    8,   26,
        8,   26,   28,   29,   42,   42,   52,   63,   29,   29,

       42,   28,   73,   76,   51,   29,   51,   51,   52,   29,
       38,   67,   38,   67,   63,  451,   38,   76,   91,   91,
       73,   92,   42,   93,   91,   94,   92,   94,   93,  214,
      135,  200,  189,  189,  214,  135,  189,   38,  215,  450,
       38,  215,  200,  449,   38,  448,   91,  447,   92,  234,
       93,   38,  234,  241,   38,  285,   38,  135,  326,  446,
      241,  326,  285,  347,  390,  406,  347,  390,  406,  455,
      455,  456,  456,  458,  458,  459,  459,  445,  444,  443,
      439,  438,  437,  436,  432,  431,  429,  428,  427,  426,
      424,  423,  422,  421,  419,  418,  417,  416,  415,  414,

      413,  412,  410,  409,  408,  407,  405,  404,  402,  400,
      399,  397,  396,  395,  394,  393,  391,  389,  388,  387,
      381,  380,  379,  378,  377,  376,  375,  373,  372,  371,
      370,  369,  368,  366,  365,  364,  363,  362,  361,  360,
      359,  356,  355,  354,  353,  352,  351,  350,  349,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      334,  333,  332,  331,  330,  329,  328,  327,  325,  323,
      322,  321,  320,  319,  318,  317,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  302,  301,  299,
      298,  297,  295,  294,  292,  291,  290,  289,  287,  284,

      283,  282,  280,  279,  278,  277,  276,  275,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  263,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      248,  247,  245,  244,  243,  242,  240,  239,  238,  237,
      235,  233,  231,  230,  229,  228,  227,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  213,  212,  211,
      209,  208,  206,  205,  204,  203,  202,  201,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  188,  187,  186,
      185,  184,  183,  182,  180,  179,  178,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,

      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   90,   83,
       79,   78,   77,   75,   74,   72,   71,   70,   69,   68,
       66,   65,   64,   62,   61,   60,   59,   58,   57,   56,
       55,   54,   53,   50,   49,   48,   45,   41,   32,   31,

       30,   27,   24,   23,   21,   19,   13,   11,    9,    4,
        3,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexrib.l"
#define INITIAL 0
#line 2 "lexrib.l"
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef WITH_DMALLOC
#include <dmalloc.h>
#endif

#include "memory.h"
#include "array.h"
#include "parserib.h"
#include "render.h"

#define YY_MALLOC_DECL

/* for ReadArchive */
typedef struct _ribstack_t
{
	int                 line_num;
	const char         *rib;
	YY_BUFFER_STATE     state;
	struct _ribstack_t *next;
} ribstack_t;

static ribstack_t *ribstack = NULL;
static const char *gribfile = NULL;

int line_num = 0;
int str_pos;

int lexrib_mode_param;
int lexrib_mode_skip;

static FILE *ribin;

void add_string_char(char c)
{
	yylval.string[str_pos++] = c;
	yylval.string[str_pos]   = '\0';
}

static void read_archive(const char *rib)
{
	FILE            *fp;
	YY_BUFFER_STATE  state;
	ribstack_t      *stack;
	ri_option_t     *opt;
	char             fullpath[1024];

	if (!rib) return;

	if (rib[0] == '\0') return;

#ifdef DEBUG
	fprintf(stdout, "ReadArchive = %s\n", rib); 
#endif
	

	opt = ri_render_get()->context->option;

	if (!ri_option_find_file(fullpath, opt, rib)) {
		fprintf(stderr,
		        "[warning] ReadArchive: Can't open RIB \"%s\"\n",
			rib);
		return;
	} else {
		fp = fopen(fullpath, "r");
		if (!fp) {
			fprintf(stderr,
				"[warning] ReadArchive: Can't open RIB ");
			fprintf(stderr,
				"\"%s\"\n", rib);
			return;
		}
	}

	stack = (ribstack_t *)ri_mem_alloc(sizeof(ribstack_t));
	stack->state = YY_CURRENT_BUFFER;
	stack->rib   = gribfile;
	stack->next  = ribstack;
	ribstack     = stack;

	state = yy_create_buffer(fp, YY_BUF_SIZE);

	/* Change reading input RIB file. */
	yy_switch_to_buffer(state);

	ribin = fp;

	/* tear down is done in <<EOF>> pattern */
}

#define YY_NO_UNPUT 1
#define YY_STACK_USED 1
#define COMMENT 1
#define STR 2

#define PARAM 3

#line 743 "lexrib.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 106 "lexrib.l"

	if (lexrib_mode_skip) {
		BEGIN INITIAL;
		lexrib_mode_skip = 0;
	}
	
	if (lexrib_mode_param) {
		BEGIN PARAM;
		lexrib_mode_param = 0;
	}

#line 906 "lexrib.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 455 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 512 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 117 "lexrib.l"
{ BEGIN COMMENT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 118 "lexrib.l"
/* skip all character */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 119 "lexrib.l"
{ line_num++; BEGIN INITIAL; 		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 120 "lexrib.l"
{ return AREALIGHTSOURCE;		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 121 "lexrib.l"
{ return ATTRIBUTE;			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 122 "lexrib.l"
{ return ATTRIBUTEBEGIN;		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 123 "lexrib.l"
{ return ATTRIBUTEEND;			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 124 "lexrib.l"
{ return CLIPPING;			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 125 "lexrib.l"
{ return COLOR;				}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 126 "lexrib.l"
{ return CONCATTRANSFORM;		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 127 "lexrib.l"
{ return COORDINATESYSTEM;		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 128 "lexrib.l"
{ return DECLARE;			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 129 "lexrib.l"
{ return DEPTHOFFIELD;			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 130 "lexrib.l"
{ return DISPLAY;			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 131 "lexrib.l"
{ return EXPOSURE;			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 132 "lexrib.l"
{ return FRAMEBEGIN;			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 133 "lexrib.l"
{ return FRAMEEND;			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 134 "lexrib.l"
{ return FRAMEASPECTRATIO;		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 135 "lexrib.l"
{ return FORMAT;			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 136 "lexrib.l"
{ return HIDER;				}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 137 "lexrib.l"
{ return IDENTITY;			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 138 "lexrib.l"
{ return ILLUMINATE;			}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 139 "lexrib.l"
{ return IMAGER;			}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 140 "lexrib.l"
{ return LIGHTSOURCE;			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 141 "lexrib.l"
{ return MOTIONBEGIN;			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 142 "lexrib.l"
{ return MOTIONEND;			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 143 "lexrib.l"
{ return OPACITY;			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 144 "lexrib.l"
{ return OPTION;			}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 145 "lexrib.l"
{ return ORIENTATION;			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 146 "lexrib.l"
{ return PERSPECTIVE;			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 147 "lexrib.l"
{ return PIXELFILTER;			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 148 "lexrib.l"
{ return PIXELSAMPLES;			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 149 "lexrib.l"
{ return POINTSPOLYGONS;		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 150 "lexrib.l"
{ return POINTSGENERALPOLYGONS;		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 151 "lexrib.l"
{ return POLYGON;			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 152 "lexrib.l"
{ return PROJECTION;			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 153 "lexrib.l"
{ return QUANTIZE;			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 154 "lexrib.l"
{ return ROTATE;			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 155 "lexrib.l"
{ return SCALE;				}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 156 "lexrib.l"
{ return SHADINGINTERPOLATION;		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 157 "lexrib.l"
{ return SHADINGRATE;			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 158 "lexrib.l"
{ return SHUTTER;			}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 159 "lexrib.l"
{ return SIDES;				}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 160 "lexrib.l"
{ return SPHERE;			}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 161 "lexrib.l"
{ return SUBDIVISIONMESH;		}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 162 "lexrib.l"
{ return SURFACE;			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 163 "lexrib.l"
{ return TRANSFORM;			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 164 "lexrib.l"
{ return TRANSFORMBEGIN;		}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 165 "lexrib.l"
{ return TRANSFORMEND;			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 166 "lexrib.l"
{ return TRANSLATE;			}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 167 "lexrib.l"
{ return RIBVERSION; 			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 168 "lexrib.l"
{ return WORLDBEGIN; 			}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 169 "lexrib.l"
{ return WORLDEND; 			}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 171 "lexrib.l"
{
			  char buf[1024];
			  sscanf(yytext, "ReadArchive \"%s\"", 
				 buf);
			  /* '\"' -> '\0' */
			  buf[strlen(buf)-1] = '\0';
			  read_archive(buf);
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 179 "lexrib.l"
{ strcpy(yylval.string, yytext);
			  return UNKNOWN;			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 181 "lexrib.l"
{ return LBRACKET;			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 182 "lexrib.l"
{ return RBRACKET;			}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 183 "lexrib.l"
{ str_pos = 0; yy_push_state(STR);	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 184 "lexrib.l"
{ add_string_char('\n');		}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 185 "lexrib.l"
{ add_string_char('\t');		}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 186 "lexrib.l"
{ add_string_char('\r');		}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 187 "lexrib.l"
{ add_string_char('\b');		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 188 "lexrib.l"
{ add_string_char('\f');		}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 189 "lexrib.l"
{ add_string_char('\"');		}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 190 "lexrib.l"
{ add_string_char('\\');		}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 191 "lexrib.l"
{
	int val = atoi(yytext + 1);
	while (val > 256) val -= 256;
	add_string_char(val);
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 196 "lexrib.l"
{ line_num++;				}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 197 "lexrib.l"
{ add_string_char(yytext[1]);		}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 198 "lexrib.l"
{ yy_pop_state(); return STRING;	}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 199 "lexrib.l"
{ add_string_char(yytext[0]);		}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 200 "lexrib.l"
{ printf("unterminated string!");	}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 201 "lexrib.l"
{
	yylval.num = atof(yytext);
	return NUM;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 205 "lexrib.l"
/* skip */
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 206 "lexrib.l"
{ line_num++;				}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 207 "lexrib.l"
{ line_num++;				}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 208 "lexrib.l"
{ printf( "[RIB parse] Illegal character: %c at line %d\n",yytext[0], line_num ); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(PARAM):
#line 209 "lexrib.l"
{ if (ribstack) {
				 ribstack_t *next = ribstack->next;

				 yy_delete_buffer(YY_CURRENT_BUFFER);
				 fclose(ribin);
				 yy_switch_to_buffer(ribstack->state);

				 gribfile = ribstack->rib;

				 free(ribstack);
				 ribstack = next;
			  } else {
				 yyterminate();
			  }
			}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 224 "lexrib.l"
ECHO;
	YY_BREAK
#line 1410 "lexrib.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 455 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 455 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 454);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 224 "lexrib.l"

