srcs=Split("""
lsh.c
main.c
""")

#my_getopt.c

Import('env')

incPath=['../base', '../transport', '../render', '../ri', '../../include']

libs=['riri', 'rirender', 'ritransport', 'ridisplay',  'ribase']
libs.append(['z'])	# zlib 

libPath=['../base', '../display', '../transport', '../render', '../ri']

p = env.CFile(target='parserib.c', source='parserib.y')
l = env.CFile(target='lexrib.c', source='lexrib.l')

#lexTarget   = CFile(target='lexrib.c', source=['lexrib.l'])
#parseTarget = CFile(target='parserib.c', source='parserib.y')

env['YACCFLAGS'].append(['-d', '-v', '-t'])
env.Depends(l, p);  # Should be lex before parse

progName='lsh'

lsh = env.Program(progName, srcs + p + l,
            CPPPATH=incPath, LIBS=libs, LIBPATH=libPath)

