import os

srcs=Split("""
accel.c
beam.c
brdf.c
bvh.c
film.c
filter.c
geom.c
hilbert.c
hilbert2d.c
ibl.c
intersection_state.c
light.c
material.c
mc.c
noise.c
polygon.c
qmc.c
raster.c
ray.c
raytrace.c
reflection.c
render.c
scene.c
shader.c
shading.c
specrend.c
spectrum.c
spiral.c
sss.c
subdivision.c
sunsky.c
texture.c
texture_loader.c
tonemap.c
triangle.c
ugrid.c
zorder2d.c
""")

Import('env')

# if env['enable_muda']:
#   srcs.append(['muda/rayaabb.c'])

incPath=['../base', '../imageio', '../transport', '../display', '../render', '../ri', '../../include']

#if env['enable_muda']:
#  incPath.append('./muda')
#  incPath.append(env['CPPPATH'])

libName='rirender'

l = env.Library(libName, srcs, CPPPATH=incPath)


if env['PREFIX'] == None:
  # install locally
  install_libdir = "../../lib"
else:
  install_libdir = os.path.join(env['PREFIX'], "lib")

install_lib = env.Install(install_libdir, l)

Default(install_lib)
