srcs=Split("""
accel.c
brdf.c
bvh.c
film.c
filter.c
geom.c
hilbert.c
hilbert2d.c
ibl.c
intersection_state.c
light.c
material.c
mc.c
noise.c
qmc.c
quadric.c
ray.c
raytrace.c
reflection.c
render.c
sampler.c
scene.c
shader.c
shading.c
sis.c
specrend.c
spectrum.c
spiral.c
subdivision.c
sunsky.c
texture.c
tonemap.c
zorder2d.c
""")

Import('env')

incPath=['../base', '../transport', '../display', '../render', '../ri', '../../include']
libName='rirender'

env.Library(libName, srcs, CPPPATH=incPath)
