import os

srcs=Split("""
transport.c
""")

# pathtrace.c

Import('env')

incPath=['../ri', '../base', '../render', '../../include']
libName='ritransport'

l = env.Library(libName, srcs, CPPPATH=incPath)

install_libdir = os.path.join(env['install_prefix'], "lib")

if env['PREFIX'] == None:
  # install locally
  install_libdir = "../../lib"
else:
  install_libdir = os.path.join(env['PREFIX'], "lib")

install_lib = env.Install(install_libdir, l)

Default(install_lib)
