Import('env')

SConscript(['base/SConscript'
           , 'ri/SConscript'
           , 'display/SConscript'
           , 'transport/SConscript'
           , 'render/SConscript'
           , 'lsh/SConscript'
           , 'gui/SConscript'
           , 'testbed/SConscript'
           ], exports='env')
