import os

srcs=Split("""
array.c
dlload.c
hash.c
list.c
log.c
matrix.c
memory.c
parallel.c
quaternion.c
queue.c
random.c
stack.c
thread.c
timer.c
util.c
vector.c
geometric.c
""")

Import('env')
#env=Environment();
#env['CC']='gcc-mp-4.2'

incPath=['../ri', '../../include']
libName='ribase'

l = env.Library(libName, srcs, CPPPATH=incPath)

if env['PREFIX'] == None:
  # install locally
  install_libdir = "../../lib"
else:
  install_libdir = os.path.join(env['PREFIX'], "lib")

install_lib = env.Install(install_libdir, l)

Default(install_lib)

