import os

srcs=Split("""
rgbe.c
image_loader.c
image_saver.c
""")

Import('env')

incPath=['../base', '../../include']

#
# JPEG
#
if env['with_jpeglib']:
	srcs.append(['jpeg.c'])
	incPath.append([env['JPEGLIB_INC_PATH']])


libName='riimageio'

l = env.Library(libName, srcs, CPPPATH=incPath)

if env['PREFIX'] == None:
  # install locally
  install_libdir = "../../lib"
else:
  install_libdir = os.path.join(env['PREFIX'], "lib")

install_lib = env.Install(install_libdir, l)

Default(install_lib)
